### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by lefuturiste** [dogue/pads#7]
I'm interested in the creation of a AUR arch linux package to simplify the installation and upgrade. (to have every packages in one place)
If you are OK, I can create the AUR package.

**Comment by dogue** [comment]
I'm absolutely okay with that. Please do. 😄

**Comment by dogue** [comment]
I created a [tag](https://github.com/dogue/pads/releases/tag/0.2.6) for 0.2.6. In case of future updates, we can have the AUR package track the tags.

**Comment by lefuturiste** [comment]
For starter I created a `-git` package https://aur.archlinux.org/packages/pads-git
Idk how it works to update it, I think since it's cloning from github, the package doesn't need update for the content, but still need update for the version.
So for the -git package and the non -git package we will probably need a github action of some kind that publish to the AUR.
It's my second time publishing to AUR, the first time was for a simple font, so I don't really known how to handle it.

**Comment by dogue** [comment]
I'm not very familiar with publishing to AUR either, but I'll do some reading this evening and see if we can figure something out. Thank you.

**Comment by dogue** [comment]
I got a Github action working to run `cargo aur` successfully, but I don't know that we're going to be able to automate updating an AUR package as it requires using an SSH keypair tied to a user account.

**Comment by dogue** [comment]
I have some other things that could benefit from AUR builds. Going to close this for now and circle back after investigating a good method for automating the process.
